### ISSUE TITLE
Exception when trying to display certain compounds

### ISSUE THREAD

**Issue by cpartl** [Caleydo/org.caleydo.view.contour#31]
An exception is thrown when trying to display certain compounds like "1486".

The exception:

```
java.lang.IllegalArgumentException: Cannot calculate bounds when 2D coordinates are missing.
    at org.openscience.cdk.renderer.BoundsCalculator.calculateBounds(BoundsCalculator.java:162)
    at org.openscience.cdk.renderer.AtomContainerRenderer.setup(AtomContainerRenderer.java:140)
    at org.caleydo.view.compounds.ui.CompoundsElement.renderSmiles(CompoundsElement.java:140)
    at org.caleydo.view.compounds.ui.CompoundsElement.layoutImpl(CompoundsElement.java:118)
    at org.caleydo.core.view.opengl.layout2.GLElement.layout(GLElement.java:306)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.layout(GLElementContainer.java:74)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.layout(GLElementContainer.java:74)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.layout(GLElementContainer.java:74)
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.layout(AnimatedGLElementContainer.java:251)
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.layout(AnimatedGLElementContainer.java:251)
    at org.caleydo.core.view.opengl.layout2.AGLElementDecorator.layout(AGLElementDecorator.java:80)
    at org.caleydo.core.view.opengl.layout2.GLElementContainer.layout(GLElementContainer.java:74)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.layoutPass(AGLElementView.java:269)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:216)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:649)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:633)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:153)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1103)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:165)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:965)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:682)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by HendrikStrobelt** [comment]
happens with disconnected compounds.. To fix this entirely every single compound needs to be rendered then all put together. Solution so far: only render largest connected component. 

Does not crash anymore.
