### ISSUE TITLE
Exception when trying to reduce elements

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#39]
In the column in which the reduce/replace/filter was triggered, the elements are not removed and the following exception is logged:

```
!ENTRY org.caleydo.core.view.ViewManager@6de59ade 1 0 2014-03-04 14:24:58.268
!MESSAGE Registering view: org.caleydo.view.relationshipexplorer.internal.GLRelationshipExplorerView@24730002
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.caleydo.core.event.EventListenerManager$AnnotationBasedEventListener.handleEvent(EventListenerManager.java:327)
    at org.caleydo.core.event.EventExecuteRunner.run(EventListenerManagers.java:166)
    at org.caleydo.core.event.EventListenerManagers$QueuedEventListenerManager.processEvents(EventListenerManagers.java:93)
    at org.caleydo.core.view.opengl.layout2.AGLElementView.display(AGLElementView.java:191)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:649)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:633)
    at com.jogamp.opengl.swt.GLCanvas$2.run(GLCanvas.java:153)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1103)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
    at com.jogamp.opengl.swt.GLCanvas$3.run(GLCanvas.java:165)
    at com.jogamp.opengl.swt.GLCanvas.runInGLThread(GLCanvas.java:965)
    at com.jogamp.opengl.swt.GLCanvas.display(GLCanvas.java:682)
    at org.caleydo.core.view.opengl.canvas.MyAnimator.run(MyAnimator.java:176)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.AssertionError
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.remove(AnimatedGLElementContainer.java:396)
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.remove(AnimatedGLElementContainer.java:392)
    at org.caleydo.core.view.opengl.layout2.animation.AnimatedGLElementContainer.remove(AnimatedGLElementContainer.java:380)
    at org.caleydo.view.relationshipexplorer.ui.list.NestableColumn.removeItem(NestableColumn.java:279)
    at org.caleydo.view.relationshipexplorer.ui.column.AEntityColumn.updateFilteredItems(AEntityColumn.java:888)
    at org.caleydo.view.relationshipexplorer.ui.column.AEntityColumn.updateChildColumnFilters(AEntityColumn.java:848)
    at org.caleydo.view.relationshipexplorer.ui.column.AEntityColumn.updateFilteredItems(AEntityColumn.java:935)
    at org.caleydo.view.relationshipexplorer.ui.column.AEntityColumn.filterChanged(AEntityColumn.java:831)
    at org.caleydo.view.relationshipexplorer.ui.column.AEntityCollection.notifyFilterUpdate(AEntityCollection.java:67)
    at org.caleydo.view.relationshipexplorer.ui.column.operation.MappingFilterUpdateOperation.triggerUpdate(MappingFilterUpdateOperation.java:35)
    at org.caleydo.view.relationshipexplorer.ui.RelationshipExplorerElement.updateMappings(RelationshipExplorerElement.java:241)
    at org.caleydo.view.relationshipexplorer.ui.RelationshipExplorerElement$1.handleIDMappingUpdate(RelationshipExplorerElement.java:90)
    at org.caleydo.view.relationshipexplorer.ui.RelationshipExplorerElement.applyIDMappingUpdate(RelationshipExplorerElement.java:228)
    at org.caleydo.view.relationshipexplorer.ui.column.operation.SelectionBasedFilterOperation.execute(SelectionBasedFilterOperation.java:47)
    at org.caleydo.view.relationshipexplorer.ui.contextmenu.FilterCommand.execute(FilterCommand.java:40)
    at org.caleydo.view.relationshipexplorer.ui.column.AEntityColumn.onHandleContextMenuOperation(AEntityColumn.java:392)
    at org.caleydo.view.relationshipexplorer.ui.list.ColumnTree$ColumnModelEventListener.onHandleContextMenuOperation(ColumnTree.java:125)
    ... 24 more
java.lang.reflect.InvocationTargetException
```

This seems to be specific to my system.

**Comment by cpartl** [comment]
Please try again
